//引入ExtJs Direct Provider
Ext.direct.Manager.addProvider(eval(SYSTEM_APPLICATION + ".ApplicationAction"));
Ext.direct.Manager.addProvider(eval(SYSTEM_APPLICATION + ".ADAction"));
Ext.direct.Manager.addProvider(eval(SYSTEM_APPLICATION + ".AttendantAction"));
Ext.direct.Manager.addProvider(eval(SYSTEM_APPLICATION + ".AppPageAction"));
Ext.direct.Manager.addProvider(eval(SYSTEM_APPLICATION + ".AuthorityAction"));
Ext.direct.Manager.addProvider(eval(SYSTEM_APPLICATION + ".AdminCompanyAction"));
Ext.direct.Manager.addProvider(eval(SYSTEM_APPLICATION + ".CompanyAction"));
Ext.direct.Manager.addProvider(eval(SYSTEM_APPLICATION + ".DeptAction"));
Ext.direct.Manager.addProvider(eval(SYSTEM_APPLICATION + ".ErrorLogAction"));
Ext.direct.Manager.addProvider(eval(SYSTEM_APPLICATION + ".GroupHeadAction"));
Ext.direct.Manager.addProvider(eval(SYSTEM_APPLICATION + ".GroupAttendantAction"));
Ext.direct.Manager.addProvider(eval(SYSTEM_APPLICATION + ".MenuAction"));
Ext.direct.Manager.addProvider(eval(SYSTEM_APPLICATION + ".UserAction"));
Ext.direct.Manager.addProvider(eval(SYSTEM_APPLICATION + ".SyncClientAction"));
Ext.direct.Manager.addProvider(eval(SYSTEM_APPLICATION + ".ScheduleAction"));
Ext.direct.Manager.addProvider(eval(SYSTEM_APPLICATION + ".SiteMapAction"));
Ext.direct.Manager.addProvider(eval(SYSTEM_APPLICATION + ".ProxyAction"));